# SITE CONFIGURATION
title: mywebsite lab # your site title
author: ghazaalnorozi # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/labexam" # the subpath of your site, e.g. /blog
url: "https://ghazaalnorozi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ghazaal
  links:
    - https://twitter.com

    - https://ghazaalnorozi.github.com
  

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Academic Calenda', link: '/Academic Calenda'}
  - {name: 'Courses', link: '/Courses'}

tagline: >
  labexam

hero_img: posts/6f8b413949e437eaae25896256c2f4af.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ghazaal2005@gmail.com # email for form submission

twitter_username: ghazaal # replace with your_twitter_username or comment to remove link from footer
github_username:  ghazaalnorozi # replace with your_github_username or comment to remove link from footer
instagram_username: gh # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: ghn # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
